version: "3.8"
services:
  deoldify-python:
    image: local/deoldify-python:dev
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FILE=/app/sample.mp4
    volumes:
      - ./models:/app/models
      - ./output:/app/output
      - ./sample.mp4:/app/sample.mp4 # input file
      # - ./colorized_frames:/app/colorized_frames
      # - ./raw_frames:/app/raw_frames
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
