version: "3.8"
services:
  deoldify-python:
    container_name: deoldify-python
    image: local/deoldify-python:dev
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FILE=/app/sample.mp4
      - FORCE_OVERWRITE_OUTPUT=True
      - INDEPENDENT_COLORIZATION=True
    volumes:
      - ./models:/app/models
      - ./output:/app/output
      - ./Night.Nurse.1931.1080p.WEB-DL.DD2.0.H.264-SbR.mkv:/app/sample.mp4 # input file
      - ./colorized_frames:/app/colorized_frames
      - ./raw_frames:/app/raw_frames
      - ./app.py:/app/app.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
